avi:
  image: srinivassurishetty/avi-lb:11
  expose: 
   - 1000
  environment:
    AVI_USER: ${AVI_USER}
    AVI_PASSWORD: ${AVI_PASSWORD}
    AVI_CONTROLLER_ADDR: ${AVI_CONTROLLER_ADDR}
    AVI_CONTROLLER_PORT: ${AVI_CONTROLLER_PORT}
    AVI_SSL_VERIFY: ${AVI_SSL_VERIFY}
    AVI_CLOUD_NAME: ${AVI_CLOUD_NAME}
    LB_TARGET_RANCHER_SUFFIX: ${LB_TARGET_RANCHER_SUFFIX}
    AVI_DNS_SUBDOMAIN: ${AVI_DNS_SUBDOMAIN}
    AVI_TENANT: ${AVI_TENANT}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-lb"
